services:
  tethys:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./tethysapp:/tethysapp
    environment:
      - DATABASE_URL=postgres://postgres:tra1512@postgres:5432/rice-leaf-diease
      - TETHYS_PORTAL_SUPERUSER_USERNAME=admin
      - TETHYS_PORTAL_SUPERUSER_PASSWORD=pass
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    networks:
      - networkName
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tethys

  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tra1512
      - POSTGRES_DB=rice-leaf-diease
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
